=pod

=encoding UTF-8

=head1 NAME

App::wu - Terminal app that provides an hourly weather forecast using Weather Underground API

=head1 VERSION

version 0.02

=head1 SYNOPSIS

This module installs the C<wu> command which prints a 36 hour weather forecast at the command line using the Wunderground API. You'll need to get a Wunderground API key (they're free) and set the environment variable C<WU_API_KEY>. Optionally you can set the environment variable C<WU_HOME_LOCATION> which sets the default location for C<wu>.

    $ wu
    Enter your location (London, UK):
    Time      ℉   ℃   Rain %  Conditions          
     2:00 AM  56  13       5  Clear                         
     3:00 AM  55  13       6  Partly Cloudy                 
     4:00 AM  55  13       6  Partly Cloudy                 
     5:00 AM  54  12       6  Partly Cloudy                 
     6:00 AM  54  12       7  Partly Cloudy                 
     7:00 AM  55  13       7  Partly Cloudy  
    ...

=head1 BUGS

Windows PowerShell and cmd.exe both corrupt the Fareinheit and Celsius degrees symbols.

=head1 SEE ALSO

=over

=item *

L<WWW::Wunderground::API> - the fabulous module that powers this app!

=item *

My PerlTricks.com L<article|http://perltricks.com/article/114/2014/9/11/Get-a-weather-report-at-the-terminal-with-Perl> about this script

=back

=head1 THANKS

Thanks to John Lifsey for writing L<WWW::Wunderground::API>

=head1 AUTHOR

David Farrell <sillymoos@cpan.org>

=head1 COPYRIGHT AND LICENSE

This software is copyright (c) 2014 by David Farrell.

This is free software; you can redistribute it and/or modify it under
the same terms as the Perl 5 programming language system itself.

=cut
